### ISSUE TITLE
Tap to open, tap again to select

### ISSUE THREAD

**Issue by ersel** [cytoscape/cytoscape.js-cxtmenu#10]
I have made a few changes to let menu stay open after user right-clicks on a node. However, selecting does not work. Current events are working only if user is hovering on a node. 
I can see this is due to options.selector being set to 'node', is there a way to watch mousemove events on the cytoscape grid?
 
https://github.com/ersel/cytoscape.js-cxtmenu

**Comment by MissChocoe** [comment]
I'd really like a contextual menu that behaves more like a traditional contextual menu. So as requested here it stays open and user go click with the left button on the item they want. On touch device, the contextual menu shows when you hold your finger on something. For me the two fingers approach doesn't work, my nodes are too small...

**Comment by maxkfranz** [comment]
Two taps pretty much defeats the purpose of having a radial menu -- the swipe gestures no longer function.  In this case, you may as well hook in a traditional list context menu with Cytoscape.js.  There are lots of libraries that do traditional menus, and it would be simple to create an extension for whichever one suits you.
