### ISSUE TITLE
Would it be possible to set the menuRadius based on the element size?

### ISSUE THREAD

**Issue by KarlJeong** [cytoscape/cytoscape.js-cxtmenu#101]
Hi there!

First of all, I do appreciate your great work and it makes me possible to deliver nice user experience to my customers.

I am currently using cxtmenu extension for few interactive commands.

The thing is, my users are able to change the size of nodes and even zoom in and out.

I set the value of menuRadius to 75 for the initial zoom level.

What happens to me is, if the user zoom in too much or increase the size of nodes more than 75, cxtmenu locates inside the node. Commands still work but it doesn't look nice.

[Nice Case]
![nicecase](https://user-images.githubusercontent.com/34212436/91956369-85b25180-ed3f-11ea-9c20-911077d82627.png)

[Bad Case1 - Node Size Changed]
![badcase1](https://user-images.githubusercontent.com/34212436/91956379-89de6f00-ed3f-11ea-90e6-29e707043ee9.PNG)

[Bad Case2 - Zoomed in Too Much]
![badcase2](https://user-images.githubusercontent.com/34212436/91956381-89de6f00-ed3f-11ea-8594-b5a98e88b2da.PNG)

What I think is if I can give a function with element parameter everything could be nice because in my case data includes the size  of element.

So I can set the different size of menuRadius for each node.

Or is there any way to bypass to overcome this matter?

**Comment by tristanidoux** [comment]
Implemented using PR #104.
