### ISSUE TITLE
Ignored attempt to cancel a touchend event with cancelable=false

### ISSUE THREAD

**Issue by sunillarsson** [cytoscape/cytoscape.js-cxtmenu#102]
There seem to be an issue with touchend events while interacting with the cytoscape 'core'-selector.
While selecting the background the event isn't cancelable, while selecting a node the event is.
This is observed on the cxtmenu demo, both on mobile and on a pc.

**Comment by maxkfranz** [comment]
I believe that only the DOM event is cancellable
