### ISSUE TITLE
Hover Event/Function menu items

### ISSUE THREAD

**Issue by cicarulez** [cytoscape/cytoscape.js-cxtmenu#135]
Hi, it would be possible to add a function to execute when the commands are hovered, as is the case for select.

ex. 

      /*
       * A function to execute when the command is hovered.
       */
      hover?: ((element: cytoscape.SingularData) => void) | undefined;

Thank you

**Comment by maxkfranz** [comment]
That sounds like a great idea for a feature.  Would you put up a pull request with your proposal?

**Comment by cicarulez** [comment]
I already did, but I didn't associate it with the issue.


Il giorno mar 10 gen 2023 alle ore 17:49 Max Franz ***@***.***>
ha scritto:

**Comment by maxkfranz** [comment]
Great, thanks.

Ref: #137

**Comment by maxkfranz** [comment]
Released as 3.5.0.  Thanks for the PR
