### ISSUE TITLE
CSS Variable support for fillColor and activeFillColor

### ISSUE THREAD

**Issue by mecharmor** [cytoscape/cytoscape.js-cxtmenu#151]
Hi cytoscape.js-cxtmenu team!

I wanted to see if its possible to support CSS variables for the keys: fillColor, and activeFillColor.

This will help enhance the modularity of this extension when trying to apply dynamic themes site-wide.
I did however notice that the `Command.contentStyle.*` color supports CSS variables so i'm guessing that is injecting some native CSS into the page rather than `fillColor` which i'm guessing parses the colors or something.

Here is a screenshot of what i'm trying to do:
![image](https://github.com/cytoscape/cytoscape.js-cxtmenu/assets/12702175/2844a535-0f35-48f1-b85e-fcaf5c4f1926)

Thanks!

**Comment by maxkfranz** [comment]
This sounds like a great idea for an enhancement PR.

**Comment by mecharmor** [comment]
if I have time i'll try to put something together
