### ISSUE TITLE
Overlap occurs when multiple menus at the same time

### ISSUE THREAD

**Issue by Ice-clean** [cytoscape/cytoscape.js-cxtmenu#167]
Hello, I am using context menu and I found that when multiple menus meet the selector at the same time, they will overlap. Is it possible to merge multiple menu options and deduplicate?

**Comment by maxkfranz** [comment]
Either don't create the overlap in the instances, or use a single instance with a commands function.

**Comment by Ice-clean** [comment]
Thx for your answer! I'm still wondering know how should I use this option if I want it to have one command on normal nodes and two commands on compound nodes?
```json
{
    "selector": "node",
    "commands": [
        {
            "enabled": true,
            "content": "one"
        }
    ]
}
{
    "selector": "$node > node",
    "commands": [
        {
            "enabled": true,
            "content": "two"
        }
    ]
}
```

**Comment by maxkfranz** [comment]
> Thx for your answer! I'm still wondering know how should I use this option if I want it to have one command on normal nodes and two commands on compound nodes?

I'd use the commands as a function
