### ISSUE TITLE
Using the context menu on Touch devices

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js-cxtmenu#17]
Hi,
I am using the circular context menu in my cytoscapeJS code. However, on tablets, it is not allowing me to hold to get the menu to appear and then click a menu item using multi-finger gestures. Is there code for touch gestures in the <b>cxtmenu</b> that can be modified to enable this ?
Or do I have to modify my cytoscapeJS code to allow for this ?

**Comment by maxkfranz** [comment]
Duplicate of #16
