### ISSUE TITLE
Allow opening menu on taphold

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-cxtmenu#2]

**Comment by maxkfranz** [comment]
Requires change in core.  Perhaps v2.4 can not trigger the drag gesture if taphold occurred.

**Comment by maxkfranz** [comment]
Simpler:

```js
node.on('taphold', function(e){
  this.ungrabify();
}).on('free', function(e){
  this.grabify();
});
```

**Comment by maxkfranz** [comment]
Requires bugfix in 2.3.11

**Comment by maxkfranz** [comment]
@Braintelligence
@AjitPS
@thachp

This should do it, but to use it you'll need to wait for 2.3.11 or build cy.js from master.

**Comment by Braintelligence** [comment]
Thanks a lot!

**Comment by AjitPS** [comment]
Thanks @maxkfranz

**Comment by AjitPS** [comment]
On a touch device, holding (taphold) with one finger allows me to drag the nodes around. However, if I continue holding a node, the radial context menu pops up (for a very short duration). Is there a way to ensure that the context menu stays visible instead of disappearing almost immediately ?
