### ISSUE TITLE
Menu stays open when left click is press while holding right click

### ISSUE THREAD

**Issue by MissChocoe** [cytoscape/cytoscape.js-cxtmenu#20]
This can be reproduced using the demo.html in version 2.1.0 of the contextual menu.

Steps:
1) Right-Click on a node so the menu shows
2) While still holding the right click, click on the node using a left click
3) Release the right click. Menu will stay displayed until you right click somewhere new (but it cannot be used anymore)

**Comment by maxkfranz** [comment]
I'll see if I can find a mouse that can reproduce this.  I only have touchpads and touchmice, so it's impossible to reproduce.

**Comment by XiaNi** [comment]
this commit should fix this issue https://github.com/XiaNi/cytoscape.js-cxtmenu/commit/babd419be4d59259f96a3366b640b57d41c630b
(made pull request)
