### ISSUE TITLE
Radial context menu - Android - selecting menu items not working

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js-cxtmenu#24]
Hi, I am testing viewing cytoscapeJS network graphs on an Android tablet. I have also implemented the cytoscapeJS circular (radial) context menu.
The radial context menu shows up on a ````taphold```` gesture. However, it stays locked on the 1st menu item and does not allow me to select the other options in the menu. I can select my 1st menu item but not any of the rest. Does this work for anyone ?

Note: This is related to https://github.com/cytoscape/cytoscape.js-cxtmenu/issues/16 and also to https://github.com/cytoscape/cytoscape.js-cxtmenu/issues/2

**Comment by maxkfranz** [comment]
This seems to fix it in the Chrome touch device simulator.  Let me know if it works for you.

**Comment by AjitPS** [comment]
@maxkfranz  Thanks, this has fixed it.
