### ISSUE TITLE
API documentation for cxtmenu, changing css properties

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js-cxtmenu#25]
Hi,
Is there any existing API documentation for the ````cxtmenu```` plugin that shows how to change its default css properties such as the size and type of the font for menuitem Text ?

<u>Note:</u> I read that it is possible to change font css for <i>itemText</i> by using the ````cxtmenu-content```` class but there are no available examples or ducmentation of the same.

**Comment by maxkfranz** [comment]
Use whatever regular CSS you'd like, i.e. `.cxtmenu-content { ... }`

**Comment by AjitPS** [comment]
Thanks @maxkfranz
