### ISSUE TITLE
Fix context menu location

### ISSUE THREAD

**Issue by daveychu** [cytoscape/cytoscape.js-cxtmenu#34]
The context menu is opened in an unusual location. This has been broken since Cytoscape version 2.5.1. See demo.html.

**Comment by maxkfranz** [comment]
It's working for me with the latest versions of Cytoscape.js and the extension

**Comment by daveychu** [comment]
The position property of the div wrapping the canvas has changed value from absolute to relative (since Cytoscape 2.5.1). Changing the property back to absolute shows the context menu in the expected location.

What browser are you testing in? I have tested this on Chrome, Firefox, IE and Edge on multiple computers and observe the same issue.

**Comment by daveychu** [comment]
Oops, I was looking at an older version. Commit 2fee0e7 seems to have fixed the problem.
