### ISSUE TITLE
Add option to disable context menu on long press

### ISSUE THREAD

**Issue by daveychu** [cytoscape/cytoscape.js-cxtmenu#35]
In some projects it might be preferred to only show the context menu on right click.

**Comment by maxkfranz** [comment]
That could be, but it makes it not work nearly as well on touch

**Comment by daveychu** [comment]
@maxkfranz Is release 2.6.0 awaiting any other fixes?

**Comment by maxkfranz** [comment]
I published it a while ago: https://www.npmjs.com/package/cytoscape-cxtmenu

It looks like the tag didn't take, so I pushed the tag again
