### ISSUE TITLE
Miss-fire of CXT Select function

### ISSUE THREAD

**Issue by blacksmithblack** [cytoscape/cytoscape.js-cxtmenu#42]
Hi .. Awesome plugin for cytoscope thanks !

I'm probably doing something wrong, but I'm finding when the menu opens over a node, the function I specify in the 'select' part of the config doesnt fire untill I click on another node, and the action is performed on the 'other' node not the original. Is this the intended behaviour or do I have a miss configuration?

This is my instantiation:

```
var cytoscape = require('cytoscape');
var jquery = require('jquery');
var cxtmenu = require('cytoscape-cxtmenu');

cxtmenu(cytoscape, jquery);
```

And this is my config:

```
// Add CXT Circular menu
      $scope.cy.cxtmenu({
        selector: 'node',
        fillColor: 'rgb(4, 77, 149)', // the background colour of the menu
        activeFillColor: 'rgb(0, 102, 204)', // the colour used to indicate the selected command
        openMenuEvents: 'cxttapstart taphold tap',
        commands: [
          {
            content: 'Create Card',
            select: function(ele){
              console.log( ele.id() );
            }
          },
          {
          content: '<span class="fa fa-star fa-2x"></span>',
            select: function(ele){
              console.log( ele.data('name') );
            }
          },
          {
            content: 'Remove',
            select: function(ele){
              console.log( ele.position() );
              $scope.cy.remove(ele);
              //$scope.cy.layout();
            }
          }
        ]
      });
```

With this example when I click on the 'Remove' section, nothing happens and then when I click on another node, the other node is removed from the graph and not the original.

Thanks once again !!!!

**Comment by maxkfranz** [comment]
The extension operated on swipe gestures.  You specified `openMenuEvents: 'cxttapstart taphold tap`, and tap is not part of a swipe gesture.  I don't think there are any other valid events than `'tapstart'` and `'cxttapstart'`.

**Comment by blacksmithblack** [comment]
Thanks ... I'll move to using the context menu
