### ISSUE TITLE
click to open,click menu item to select 

### ISSUE THREAD

**Issue by BardMa** [cytoscape/cytoscape.js-cxtmenu#43]
hello,
I want to achieve an effect, 
click to open,click menu item to select ,
can you help me?

**Comment by maxkfranz** [comment]
From the readme:

> This plugin creates a widget that lets the user operate circular context menus on nodes in Cytoscape.js. The user swipes along the circular menu to select a menu item and perform a command on the node of interest.

If you want a traditional menu, then use something else:

- https://github.com/cytoscape/cytoscape.js-qtip
- https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus
- Or just use your favourite context menu lib directly.

**Comment by BardMa** [comment]
Thank you very much！I like this menu style。I will modify the code to finish it

**Comment by maxkfranz** [comment]
@BardMa OK, please consider making a pull request with your new option.  Thanks!

**Comment by KonradHoeffner** [comment]
@maqi1520: We also need this functionality, were you successful? Did you create a pull request?

**Comment by maqi1520** [comment]
@KonradHoeffner My website is more complicated, I used [react](https://reactjs.org/) and [d3.js](https://d3js.org/) to achieve my needs.
