### ISSUE TITLE
IE9 error: Object expected if(redrawing) { raf(redraw) }

### ISSUE THREAD

**Issue by eelco2k** [cytoscape/cytoscape.js-cxtmenu#49]
When using IE9 (actually IE10 in emulation mode with  <meta http-equiv="X-UA-Compatible" content="IE=9">) cxtmenu.js is complaining about Object expected.

this is because IE9 has (i guess) no support for: 
var raf = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame;

So implement a polyfill for IE9.

[requestAnimationFrame polyfill](https://www.paulirish.com/2011/requestanimationframe-for-smart-animating/)

**Comment by eelco2k** [comment]
after adding the requestAnimationFrame polyfill i'm getting the same problem as ticket #50  in the demo.html of cytoscape.js-cxtmenu

**Comment by maxkfranz** [comment]
If you want to add a polyfill for out of date browsers, then please make a pull request.

**Comment by maxkfranz** [comment]
You can just use your own global polyfill.

**Comment by eelco2k** [comment]
yes i used a polyfill. thnx!
