### ISSUE TITLE
Different behaviour IE7/8 and IE9/10

### ISSUE THREAD

**Issue by eelco2k** [cytoscape/cytoscape.js-cxtmenu#50]
The contextmenu behaves differently on IE7/8 than on IE9/10. 

A context menu only works once in IE9/10 when pressed on a node with contextmenu bound to it.
the standard "windows" context menu appears instead. And the contextmenu stays visible after selecting / not selecting an item in the context menu.

You can try by adding: 
`<meta http-equiv="X-UA-Compatible" content="IE=9">`
or
`<meta http-equiv="X-UA-Compatible" content="IE=8">`

in the head tag.

When one contextmenu stays active all other nodes with an contextmenu cannot be used anymore. And the only contextmenu which works on all nodes is the standard windows contextmenu.

See image below:
<img width="639" alt="schermafbeelding 2016-11-30 om 17 02 05" src="https://cloud.githubusercontent.com/assets/878103/20759955/cdaec262-b71e-11e6-956f-3cc5128083ed.png">

I used version 2.9.2

I cannot use IE=10 or edge in de meta http-equiv because there is an bug in IE10 when i use background-images as SVG's (in this case i use label text as svg background images. in base64.) they appear empty. (see browser bug issue in cytoscape ticket: [#795](https://github.com/cytoscape/cytoscape.js/issues/795) ).  For newer browsers (IE Edge and chrome + FF) i'm using the foreignobject in the SVG background so that i can use html in the labels.

**Comment by maxkfranz** [comment]
Nothing is going to work with IE<9, as it doesn't support canvas

**Comment by eelco2k** [comment]
I have added a video where i reproduce the problem:

[vimeo cxtmenu IE9 & 10 problem](https://vimeo.com/193869707)

**Comment by eelco2k** [comment]
another demo to demonstratie IE9/10 bug: used the cxtmenu demo.html file this time.

[(https://vimeo.com/193874830)]

**Comment by eelco2k** [comment]
After some debugging i noticed that the way the binding are connected to the core extension of cytoscape gives me the errors...

`var bindings = {
                on: function(events, selector, fn) {
                    var _fn = fn; `

and then in
`bindings
                    .on(options.openMenuEvents, options.selector, function(e) {`

when i change it to:
`cy.on(options.openMenuEvents, function(e) {`
and remove all the `options.selector` in all bindings 

I can reopen the contextmenu as much as i want.

**Comment by maxkfranz** [comment]
You're not going to get any visualization technology to work in IE8 -- except Flash.  No version of IE supports SVG properly.  Canvas works only in IE9+: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement

Those compatibility modes aren't accurate and match *no* version of IE proper.

If you really want to support a browser that is the better part of a decade out of date, I'd really recommend using Flash.

**Comment by eelco2k** [comment]
The video above reproduces the problem in IE9&10 which has nothing to do with SVG because the cxtmenu is pure canvas. Another problem is that I cannot use IE11 because of the SVG background issue. But that's not the problem i want to raise in this issue. 

I only want to say that users who only have IE9 or 10 the cxtmenu with rightclick just doesn't behave correctly. If the support of those browsers are not within the scope of cxtmenu then i can understand. but it would be nice if for those usecases (cxtmenu with IE9/10) would work without the interference of the default windows contextmenu. And that the cxtmenu functionality then after one time rightclick is gone.

**Comment by maxkfranz** [comment]
The extension already prevents the system context menu from showing up.  Otherwise, you'd see it in Chrome and Firefox.  If there are bugs in IE itself, there's nothing I can do.
