### ISSUE TITLE
Click `node` or `edge` doesn't work right away

### ISSUE THREAD

**Issue by lukejpreston** [cytoscape/cytoscape.js-cxtmenu#51]
You can set the `selector` as `node` and then select a node, menu opens fine. Then select a command. It does not trigger the `command` until you interact with the node again, either moving node or clicking the node.

the same is true for edge

This is not true when `selector` is equal to `core`

here is my sample code

```js
cy.cxtmenu({
  selector: 'node',
  commands: [{
    content: 'bg1',
    select: function() {
      console.log( 'bg1' );
    }
  }
})
```

I want the select function to trigger immediately after selecting an option in the menu

**Comment by maxkfranz** [comment]
Definitely a bug.  Thanks for the PR

The change should be in the just published 2.9.4 release
