### ISSUE TITLE
Left click opens menu but doesn't trigger options

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js-cxtmenu#56]
I set `openMenuEvents: 'cxttapstart taphold'` and can now open the context menu with either the right or the left mouse button. However when opening it with the left mouse button, it takes longer to open and it doesn't execute any of the chosen functions.

I use cytoscape.js 2.7.16, cytoscape.js-cxtmenu 2.9.6 and Firefox 52.0.1.

**Comment by maxkfranz** [comment]
I tried the demo page, and it's working on Firefox and Chrome.

What options are you using?

**Comment by KonradHoeffner** [comment]
My options are:

	var defaults = {
		menuRadius: 100,
		selector: 'node', 
		commands: [...	],
		fillColor: 'rgba(255, 255, 50, 0.35)',
		activeFillColor: 'rgba(255, 255, 80, 0.35)',command
		openMenuEvents: 'cxttapstart taphold', separated)
		itemColor: 'white', 
		itemTextShadowColor: 'gray',
		zIndex: 9999, 
	};
	var cxtmenuApi = cy.cxtmenu(defaults);

**Comment by maxkfranz** [comment]
You have syntax mistakes in your options object.
