### ISSUE TITLE
Misplaced and compressed menu

### ISSUE THREAD

**Issue by DavidFlamini** [cytoscape/cytoscape.js-cxtmenu#60]
Hello, any idea why this could be happening? or maybe how to disable menu background rendering as a workaround?  ![screenshot 2017-05-17 18 34 14](https://cloud.githubusercontent.com/assets/15835360/26177393/d0726716-3b2f-11e7-902f-99db5ffe179e.png)

**Comment by maxkfranz** [comment]
Could you post some code or a jsbin demo that reproduces the issue?

**Comment by DavidFlamini** [comment]
Sure, I'll try to put something up but I'm using Angular2 and I'm new to it.

In the meantime I patched cytoscape-ctxmenu.js like this:
line 165:     width: containerSize + 1300 +  'px',
line 198:     left: '7.5%',

which works even when the canvas size changes (i.e. when the window size changes), but I wouldn't know why, it was trial and error.
