### ISSUE TITLE
How to unregister the extension?

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js-cxtmenu#62]
I register the extension with:
```
cxtmenu(cytoscape)
```

But how to unregister?

Unregistering is needed in conjunction with Webpack's hot module replacement.

If not unregistered the extension might get registered again while development, causing this error:
```
Can not register `cxtmenu` for `core` since `cxtmenu` already exists in the prototype and can not be overridden
```

**Comment by maxkfranz** [comment]
There would have to be a new core function for that.  An extension doesn't modify anything; it just requests the core to do so.

Anyway, I don't think that message should give you any problems.  It's just a console message, not an exception.  So, it shouldn't prevent your code from progressing either way.

**Comment by jri** [comment]
> Anyway, I don't think that message should give you any problems. It's just a console message, not an exception. So, it shouldn't prevent your code from progressing either way.

Unfortunately I can't acknowledge that.

When my application's rendering (vue) component is hot replaced (by webpack-dev-server) the cxtmenu extension is registered again, which fails. 
No graph rendering takes place then. The canvas remains empty.

The Cytoscape instance seems corrupted somehow then.
Possibly this is because `setExtension()` terminates early, returning the result of `overrideErr()` instead the extensions map (but I'm not sure about this).

```
function setExtension(type, name, registrant) {

  var ext = registrant;

  var overrideErr = function overrideErr(field) {
    util.error('Can not register `' + name + '` for `' + type + '` since `' + field + '` already exists in the prototype and can not be overridden');
  };

  if (type === 'core') {
    if (Core.prototype[name]) {
      return overrideErr(name);
    } else {
      Core.prototype[name] = registrant;
    }
  } else if
     ...
  }

  return util.setMap({
    map: extensions,
    keys: [type, name],
    value: ext
  });
}
```

In conjunction with hot module replacement the double extension registration occurs because of this: when hot replaced my renderer component creates a new Cytoscape instance. On the other hand the Cytoscape modules itself are **not** replaced. The state of `Core.prototype` remains intact, and causes the override error.

With browser reload the application works fine again, but this removes the benefit of hot module replacement.

In order to work with hot module replacement Cytoscape Core should provide an explicit `unregister` call.

**Comment by jri** [comment]
Meanwhile I investigated it further and found I was wrong here:

> The Cytoscape instance seems corrupted somehow then.
Possibly this is because setExtension() terminates early, returning the result of overrideErr() instead the extensions map (but I'm not sure about this).

Actually it's due to my application, not Cytoscape, that the canvas is not rendered when hot replaced.
Sorry for bothering you.

But still, Cytoscape reports the console message as an *error*, not as a warning which I can safely ignore. That gave me the (wrong) impression the problem is in Cytoscape.

![screen shot 2018-01-21 at 13 33 04](https://user-images.githubusercontent.com/120337/35194189-b2d14cc4-feaf-11e7-8be7-9dcab7576061.png)

Cytoscape should display that console message as a *warning*, not as an error.
That would have avoided the entire misunderstanding in the first place.

And still I think an explicit `unregister` Core call is desired.
This way the `overrideErr` could be prevented in the first place.

Thank you for the support!

**Comment by sirbris** [comment]
I get the same error "Can not register `cxtmenu` for `core` since `cxtmenu` already exists in the prototype..." but am not able to check, if cxtmenu was already registered. 
Setting "Object.getPrototypeOf( cy )[ cxtmenu ] = null;" before did not work.

How can I avoid this registration here if it has been done already?
`cytoscape.use(cxtmenu);`

Thank you very much in advance!

**Comment by marcosalpereira** [comment]
After countless attempts, I tried the code below and it worked for me:
```
import cxtmenu from 'cytoscape-cxtmenu';
cxtmenu.register = () => {};
```

**Comment by MirkoLenz** [comment]
For me, the following worked:

```typescript
import cytoscape from "cytoscape";
import cxtmenu from "cytoscape-cxtmenu";

cytoscape.use(cxtmenu);
// eventually other calls to cytoscape.use()
cytoscape.use = () => {};
```
