### ISSUE TITLE
Using typescript with ctxmenu - TypeError: this.cy.ctxmenu is not a function

### ISSUE THREAD

**Issue by bdparrish** [cytoscape/cytoscape.js-cxtmenu#70]
I get `TypeError: this.cy.ctxmenu is not a function` when trying to add ctxmenu to cytoscape graph.

```typescript
import * as cytoscape from 'cytoscape';
import * as ctxmenu from 'cytoscape-cxtmenu';

... removed for brevity ...
        this.cy = cytoscape({
            container: this.cytoscapeElem.nativeElement,
            elements: [
                { data: { id: 'a' } },
                { data: { id: 'b' } },
                { data: { id: 'ab', source: 'a', target: 'b' } }
            ],
            style: [
                {
                    selector: 'node',
                    style: {
                        'background-color': '#666',
                        'label': 'data(id)'
                    }
                },
                {
                    selector: 'edge',
                    style: {
                        'width': 3,
                        'line-color': '#ccc',
                        'target-arrow-color': '#ccc',
                        'target-arrow-shape': 'triangle'
                    }
                }
            ],
            layout: {
                name: 'cose'
            }         
        });
        
        let defaults = {
            menuRadius: 100, // the radius of the circular menu in pixels
            selector: 'node', // elements matching this Cytoscape.js selector will trigger cxtmenus
            commands: [ // an array of commands to list in the menu or a function that returns the array
              /*
              { // example command
                fillColor: 'rgba(200, 200, 200, 0.75)', // optional: custom background color for item
                content: 'a command name' // html/text content to be displayed in the menu
                contentStyle: {}, // css key:value pairs to set the command's css in js if you want
                select: function(ele){ // a function to execute when the command is selected
                  console.log( ele.id() ) // `ele` holds the reference to the active element
                },
                enabled: true // whether the command is selectable
              }
              */
            ], // function( ele ){ return [ /*...*/ ] }, // example function for commands
            fillColor: 'rgba(0, 0, 0, 0.75)', // the background colour of the menu
            activeFillColor: 'rgba(1, 105, 217, 0.75)', // the colour used to indicate the selected command
            activePadding: 20, // additional size in pixels for the active command
            indicatorSize: 24, // the size in pixels of the pointer to the active command
            separatorWidth: 3, // the empty spacing in pixels between successive commands
            spotlightPadding: 4, // extra spacing in pixels between the element and the spotlight
            minSpotlightRadius: 24, // the minimum radius in pixels of the spotlight
            maxSpotlightRadius: 38, // the maximum radius in pixels of the spotlight
            openMenuEvents: 'cxttapstart taphold', // space-separated cytoscape events that will open the menu; only `cxttapstart` and/or `taphold` work here
            itemColor: 'white', // the colour of text in the command's content
            itemTextShadowColor: 'transparent', // the text shadow colour of the command's content
            zIndex: 9999, // the z-index of the ui div
            atMouse: false // draw menu at mouse position
        };

        this.cy.ctxmenu(defaults);
```

**Comment by EniesLobby** [comment]
Same issue

**Comment by maxkfranz** [comment]
Is there a `cytoscape.use(ext)` after `import`?

**Comment by EniesLobby** [comment]
Hi maxkfranz,

yes, the code's structure is similar to the author's one with cytoscape.use(ext) in it.

in component side:
```
import * as cytoscape from 'cytoscape';
import * as cxtmenu from 'cytoscape-cxtmenu';
cytoscape.use(cxtmenu);

```

in typings.d.ts:

`declare module 'cytoscape-cxtmenu';`

in angular.json scripts are also included.

It does not see cy.ctxmenu();

Thank you for your help!

**Comment by maxkfranz** [comment]
If the TS import is the same as the ES import, then you need to use the default export rather than *.

**Comment by maxkfranz** [comment]
```
import cytoscape from 'cytoscape';
import cxtmenu from 'cytoscape-cxtmenu';

cytoscape.use( cxtmenu );
```

**Comment by kanakl** [comment]
I have same issue. I have error message in visual sutido code "Property 'cxtmenu' does not exist on type 'Core'". Is it possible use it in typescript? I try add to index.d.ts this:
 declare module 'cytoscape-cxtmenu' {
    const ext: cytoscape.Ext;
    export = ext;
}
But still not working.

**Comment by EHadoux** [comment]
Isn't it because it's ```cxtmenu``` and not ```ctxmenu```?

**Comment by canbax** [comment]
I managed to use cytoscape.js-context-menus extension (https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus) on angular 7 project.

I added "node_modules/cytoscape-context-menus/cytoscape-context-menus.css" to styles of the project inside angular.json file and use it as suggested

**Comment by wasiftdh** [comment]
> I managed to use cytoscape.js-context-menus extension (https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus) on angular 7 project.
> 
> I added "node_modules/cytoscape-context-menus/cytoscape-context-menus.css" to styles of the project inside angular.json file and use it as mentioned in the readme of the extension

I did the same but its still giving me error this.cy.contextMenu() is not a function in angular 7.

**Comment by ErnestManukyan** [comment]
I have same issue, when trying to integrate ctxmenu in my angular project.
So, the issue is closed, but I could not understand the solution.
Please help me !

**Comment by dmitrioligy** [comment]
import cxtmenu from 'cytoscape-cxtmenu';
cytoscape.use(cxtmenu);
...
let cy = cytoscape({ opt });
cy.cxtmenu({ cxtOpt });   

**Can not register `cxtmenu` for `core` since `cxtmenu` already exists in the prototype and can not be overridden**

Alternative

let cy = cytoscape({ opt });
cy.cxtmenu({
            selector: 'node, edge', 
...

**Uncaught (in promise) TypeError: cy.cxtmenu is not a function**

I haven't had any luck. 

I am using Svelte & Sapper. I have the graph working fine without cxtmenu, adding it in, it breaks. Any feedback would help!

**Comment by Jobvdb** [comment]
So, was anyone able to come up with a solution?

**Comment by blumTom** [comment]
Had the same issue. Solved it by calling cxtmenu not on the module but on the instance of cytoscape.
