### ISSUE TITLE
Cytoscape-cxtmenu.js is in conflict with Cytoscape-edgehandles.js

### ISSUE THREAD

**Issue by HappyTom** [cytoscape/cytoscape.js-cxtmenu#73]
After use Cytoscape-edgehandles.js，the command of Cytoscape-cxtmenu.js can't be selected.Why?

**Comment by maxkfranz** [comment]
Please link to a minimal demo that reproduces your issue.

**Comment by HappyTom** [comment]
I have solved the problem，thank you~
