### ISSUE TITLE
Show  different commands when invoked with Alt key

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js-cxtmenu#76]
I want to show different commands when the user invokes the menu while holding the Alt-key.

One way to enable this would be passing the (mouse) event that invoked the menu to the `commands` function. The application would use it as follows then:

```
commands: (ele, e) => e.altKey ? [...] : [...]
```

Or can I do it already in another way?

**Comment by jri** [comment]
Meanwhile I solved this outside Cytoscape. I capture mousdown events, read its `altKey` prop and set a global app state. The `commands` function operates on this global state then. Event capturing is done with `capture=true` so my handler sees the event *before* Cytoscape.

Passing the event  directly to `commands` might be useful anyways.

**Comment by maxkfranz** [comment]
It might be better to keep that logic outside of the extension for now.  Depending on how the extension is used, there might not be an event that has a usable `altKey` value.

**Comment by jri** [comment]
OK. Thanks for response!
