### ISSUE TITLE
Can not register 'cxtmenu'

### ISSUE THREAD

**Issue by cuilongsheng** [cytoscape/cytoscape.js-cxtmenu#80]
Error: Can not register 'cxtmenu' for core since cxtmenu already exists in the prototype and can not be overridden
at error (cytoscape.cjs.js?504e:810)
Question: 
In my React project, how can I use 
{
  let menu = cy.cxtmenu( someOptions );
  menu.destroy();
}
to clear my error.

**Comment by maxkfranz** [comment]
Don't register the extension twice
