### ISSUE TITLE
incompatible ie11

### ISSUE THREAD

**Issue by zxxzzzzz** [cytoscape/cytoscape.js-cxtmenu#91]
can not use in ie 11,but old version can use in ie11.

**Comment by zxxzzzzz** [comment]
Through investigation，found that
```
 var pageX = (isTouch ? origE.touches[0].pageX : origE.pageX) - window.scrollX;
      var pageY = (isTouch ? origE.touches[0].pageY : origE.pageY) - window.scrollY;
```
scrollX can use in ie11.In ie11 should use pageXOffset

**Comment by maxkfranz** [comment]
Would you be open to making a pull request for pageXOffset/pageYOffset and testing this change in IE 9 and up?

Ref : https://developer.mozilla.org/en-US/docs/Web/API/Window/pageXOffset
