### ISSUE TITLE
What could explain a misaligned overlay?

### ISSUE THREAD

**Issue by tunesmith** [cytoscape/cytoscape.js-cxtmenu#97]
On my blank test screen, cxtmenu appears perfectly aligned. But when I deploy it to my website - it is exported as a react component that is inside a div that is inside a surrounding div - the menu's interaction overlay appears misaligned, to the right, a hundred pixels or so. All other non-cxtmenu interactions are aligned correctly.

Trying to upload an animated gif here; not sure if github supports it.

![cxtmenu](https://user-images.githubusercontent.com/31303/81053743-6af7cb00-8e7a-11ea-9a61-370ebc9bb2d3.gif)

**Comment by tunesmith** [comment]
I believe it may be a conflict with my surrounding stylesheet. I will update and close here if I can confirm that.

**Comment by tunesmith** [comment]
The issue is that the page's html: { } css has padding: 0 0 0 50px;  If I comment that out, the menu mouse actions are in the right place. However, commenting it out screws up the surrounding website design. Is there a way to adjust the cxtmenu css to work around this?

Not sure if this is a bug, but outside of cxtmenu, the mouse interactions are all in the right place.

**Comment by tunesmith** [comment]
I was able to work around this by avoiding "padding" in the distant ancestor, and instead using "margin" in that ancestor's child (the not-quite-as-distant ancestor). I am not sure if this is a bug, so I will leave it open. If Cytoscape consortium folks believe this to be in the category of "site owners are responsible for their own css", please feel free to close.

**Comment by maxkfranz** [comment]
Is there an approach to avoid issues like this that would work generally?  There are so many layout css properties that I’m not sure whether it’s tractable to try to work around each one individually.

**Comment by tunesmith** [comment]
I assumed max's question was for other cityscape people and not for me, but my own sense is that since this behavior happens with cxtmenu and not the cytoscape graph itself (otherwise both would have been misaligned), then this suggests it is an opportunity to improve cxtmenu's handling of this scenario in a more general sense.

**Comment by maxkfranz** [comment]
If anyone in the consortium or the community has an approach to address this in a general way, then they’re welcome to make a pull request for it.  I am not aware of a general approach that would work in all supported browsers.
